---
# tasks file for apache2

 - name: install apache2
   apt: name={{item}} state=present update_cache=yes
   with_items:
       - apache2
       - libapache2-mod-wsgi
       - python-pip
       - python-virtualenv
       - python-mysqldb
 - name: ensure Apache started
   service: name=apache2 state=started enabled=yes

 - name: ensure mod-wsgi enabled
   apache2_module: state=present name=wsgi
   notify:
      restart apache2
